version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./app/temp-images:/app/temp-images
    depends_on:
      - db
    links: 
      - "db:database"
    ports: 
      - "8080:8080"
    env_file:
      - 'variables.env'
    restart: on-failure
  db:
    build: ./db
    env_file:
      - 'variables.env'