version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./app/temp-images:/app/temp-images
    depends_on:
      - db
    links: 
      - "db:database"
    ports: 
      - "8080:8080"
  db:
    build: ./db
    environment:
      - DB_USER=userdb
      - DB_PASSWORD=pass
      - DB_DATABASE=image_server
      - POSTGRES_USER=user